config/routes.rb
Rails.application.routes.draw do

  get 'pages/contact'

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, controllers: { registrations: "registrations"}
resources :posts do
	resources :comments
end
	

root "posts#index"

get '/about', to: 'pages#about'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def create
	@post = Post.find(params[:post_id])
	@comment = @post.comments.create(params[:comment].permit(:name, :body))

	redirect_to post_path(@post)
end

def destroy
	@post = Post.find(params[:post_id])
	@comment = @post.comments.find(params[:id])
	@comment.destroy

	redirect_to post_path(@post)
end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end


def about
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		
		if @post.save
			redirect_to @post
		else
			render 'new'
		end	
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit

		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path

	end

	private
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if ((User.count == 2) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 2
      redirect_to new_user_session_path
    end  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

<% if user_signed_in? %>
	<p><%= link_to 'Delete', [comment.post, comment],
								  method: :delete,
								  class: "button",
								 	data: { confirm: 'Are you sure?' } %> </p>
	<% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post,@post.comments.build]) do |f| %>
<p>
	<%=f.label :name %> <br>
	<%=f.text_field :name %>

</p>

<p>
	<%=f.label :body %> <br>
	<%=f.text_area :body %>

</p>
<br>
<p>
	<%= f.submit %>

</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
  
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'true' %>
    <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
    <link href="https://fonts.googleapis.com/css?family=Prata" rel="stylesheet"> 
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'true' %>
     
  </head>
  <body>  
<div class="nav-side-menu">
  <div class="brand">
                      <%= link_to root_path do %>
                      <%= image_tag "logo.png" %>
                      <% end %>
                      </div>
<div class="brand">Cil van den Brink </div><br>


                    <% if user_signed_in? %>
                      <div class="optin">
                        <%= link_to "New Post", new_post_path, :class => "button" %>
                        <%= link_to "Log Out", destroy_user_session_path, :class => "button", method: :delete %>﻿
                      </div>
                    <% end %>
<i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
<div class="menu-list">
<ul id="menu-content" class="menu-content collapse out">


<label class="category" >Website</label>
<li ><%= link_to "Blog", root_path %></li>
<li ><%= link_to "About", about_path %></li>


<label class="category">Social</label>
<li ><a href="https://www.linkedin.com/in/cilvandenbrink">LinkedIn</a></li>
<li ><a href="https://www.instagram.com/meiramsterdam/">Instagram</a></li>
<li ><a href="hhttps://www.facebook.com/systeempraktijk">Facebook</a></li>
<li ><a href="mailto:systeempraktijk@outlook.com">Email</a></li>
</ul>

                    <div id="footer" id="menu-content" class="menu-content collapse out" >
                        <p><strong>Systeempraktijk Amsterdam: </strong><br>
                          'De Pijp': Therese Schwartzestraat 11c, 1073 JH<br> Amsterdam,<strong>06-26810240</strong></p><br>
                        <p><strong>Systeempraktijk Lelystad centrum:</strong><br>
                         Reaalhof 31d , 8232 VW Lelystad,<strong><br>06-26810240</strong></p><br>
                            <% if !user_signed_in? %>
                            <p ><%= link_to "Admin Login", new_user_session_path%>
                            <% end %>
                    </div>
</div> 
</div>

                <div class="container" id="main">
                  <div class="row">
                    <div class="col-md-12">
                      <div>
                        <% if current_page?(root_path) %>
                        <%= link_to "All Posts", root_path %>
                        <% elsif current_page?(about_path) %>
                        <p>About</p>
                        <% else %>
                        <%= link_to "Back to All Posts", root_path %>
                        <% end %>

                        <% flash.each do |name, msg| %>
                        <%= content_tag(:div, msg, class: "alert") %>
                        <% end %>
                      </div>
        
      <%= yield %>  
      
                    
</div>
</div>
</div>

    
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<%= image_tag "profile.png" %>
	</div>

	<div id="content">
		<h1>Hey, I'm Mackenzie Child</h1>
		<p>Specialties: Emotionally Focused Couples Therapy (EFT), Familytherapy, couples therapy, individual systemic psychotherapy, transcultural therapy. <br><br>

With a background in (transcultural) systemic psychotherapy, EFT and a long experience in cognitive behavioural therapy (CBT) I created a mixed model (systemic - CBT). 
In my practice I work with couples/families and treat family/couples issues as well as patients with psychological issues through systemic-CGT therapy. Most of the clients in 'Systeempraktijk' come for couples therapy (specific couples or family related questions). <br><br>

Within Group4People and the U-Center (clinic in Epen) I work within a team and see mostly patients with individual psychological issues. Here I work together in a team with psychiatrists and other therapist.</p>
	</div>
</div>

app/views/pages/contact.html.erb
<h1> Contact </h1>

app/views/posts/_form.html.erb


<%= form_for @post do |f| %>
	<% if @post.errors.any? %>
	<div id="errors">
		<h2><%= pluralize(@post.errors.count, "error") %> Prevented this post from saving </h2>
		<ul>
			<% @post.errors.full_messages.each do |msg| %>
			<li><%= msg %> </li>
			<% end %>
		</ul>	

	</div>
	<% end %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title %>
</p>

<p>
<%= f.label :body %><br>
<%= f.cktext_area :body %>
</p>

<p>
<%= f.submit %>
</p>

<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
<h1>Edit Post</h1>

<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post_wrapper">
	<h2 class="title"><%= link_to post.title, post %></h2>
	<p class="date"> <%= post.created_at.strftime("%B, %d, %Y") %></p>
</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
<h1>New Post</h1>

<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
<h1 class="title">
<%= @post.title %>

</h1>

<p class="date">
	Submitted <%= time_ago_in_words(@post.created_at) %> Ago
	<% if user_signed_in? %>
	| <%= link_to 'Edit', edit_post_path(@post) %>
	| <%=  link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
<% end %>
</p>

<p class="body">
	<%= raw @post.body %>
	
</p>

<div id="comments">
	<h2> <%= @post.comments.count %> Comments</h2>
	<%= render @post.comments %>

	<h3>Add a comment:</h3>
	<%= render "comments/form" %>


</div>
</div>